RT::Config fix for proper loading when Fcntl is loaded.
Date: Mon, 8 Feb 2010 19:47:04 -0800
From: Ivan Kohler <ivan-rt-devel@420.am>
To: rt-devel@lists.bestpractical.com
Cc: rt@northpb.com
Subject: [Rt-devel] [patch] RT 3.8 bug when using Fcntl perl module

Hi,

I find myself having recently encountered the bug indicated here:

http://lists.fsck.com/pipermail/rt-users/2009-September/061167.html

(including "use Fcntl;" in a script which uses the RT libraries
and attempts to LoadConfig() and Init() causes io error out with an
error: "Couldn't load RT config file RT_SiteConfig.pm: Not a SCALAR
reference")

The following patch to lib/RT/Config.pm should fix the problem and allow
use of RT libraries while Fcntl (and probably other similar modules
which export symbols) are loaded concurrently: