Restrict Name checks to objects with Name and only when id is not numeric
92dc904 updated the id check in Shredder to handle the case where $id is actually a Name.
However, it breaks the case where $id is not a Name, which could produce errors like:

error: RT::Ticket::Name Unimplemented in RT::Shredder

This commit fixes it to:

* Not check Name if $id is numeric.
* Not check Name if object doesn't have it.