Fix the file name in the schema missing error message
Previously, there was "$file = $self->GetVersionFile( $dbh, $file )", so
$file could be undef if the version file couldn't be found. Sadly, we
used the same $file in the upcoming missing error message, so we got:

    ERROR: Couldn't find schema file(s) '*'